import { column, Schema, Table } from "@powersync/web";

const syncColumns = {
  archived_at: column.text,
  client_updated_at: column.text,
  created_at: column.text,
  created_by_device_id: column.text,
  deleted_at: column.text,
  hidden_reason: column.text,
  revision: column.integer,
  server_updated_at: column.text,
  updated_at: column.text,
  updated_by_device_id: column.text,
  user_id: column.text,
};

export const yasumiPowerSyncSchema = new Schema({
  areas: new Table({
    ...syncColumns,
    name: column.text,
    sort_order: column.integer,
  }),
  items: new Table(
    {
      ...syncColumns,
      area_id: column.text,
      deadline_at: column.text,
      deadline_date: column.text,
      deadline_time: column.text,
      deadline_time_zone_mode: column.text,
      deadline_timezone: column.text,
      estimated_effort: column.integer,
      generated_from_item_id: column.text,
      importance: column.integer,
      item_type: column.text,
      note: column.text,
      planned_work_date: column.text,
      pressure_metadata: column.text,
      quick_add_parse_result: column.text,
      quick_add_source_text: column.text,
      recurring_anchor_date: column.text,
      recurring_sequence: column.integer,
      recurring_template_id: column.text,
      reminder_at: column.text,
      reminder_date: column.text,
      reminder_intent: column.text,
      reminder_time: column.text,
      reminder_time_zone_mode: column.text,
      review_date: column.text,
      scheduled_date: column.text,
      scheduled_time: column.text,
      scheduled_time_zone_mode: column.text,
      status: column.text,
      title: column.text,
    },
    {
      indexes: {
        area: ["area_id"],
        status: ["status"],
        type: ["item_type"],
      },
      trackPrevious: {
        columns: ["status", "deleted_at", "archived_at", "hidden_reason", "revision"],
        onlyWhenChanged: true,
      },
    },
  ),
  operation_history: new Table(
    {
      created_at: column.text,
      created_by_device_id: column.text,
      event_type: column.text,
      idempotency_key: column.text,
      item_id: column.text,
      new_value: column.text,
      previous_value: column.text,
      reason: column.text,
      recurring_template_id: column.text,
      user_id: column.text,
    },
    { insertOnly: true },
  ),
  recurring_task_templates: new Table({
    ...syncColumns,
    area_id: column.text,
    completed_count: column.integer,
    end_after_count: column.integer,
    end_date: column.text,
    end_type: column.text,
    frequency: column.text,
    generated_task_defaults: column.text,
    interval: column.integer,
    next_sequence: column.integer,
    note: column.text,
    recurrence_basis: column.text,
    reminder_rule: column.text,
    scheduled_time: column.text,
    start_date: column.text,
    status: column.text,
    title: column.text,
    weekdays: column.text,
  }),
  rejected_write_context: new Table(
    {
      action: column.text,
      client_action_id: column.text,
      created_at: column.text,
      error_code: column.text,
      field_errors: column.text,
      idempotency_key: column.text,
      retryable: column.integer,
      row_id: column.text,
      table_name: column.text,
    },
    { localOnly: true },
  ),
  user_settings: new Table({
    client_updated_at: column.text,
    created_at: column.text,
    created_by_device_id: column.text,
    date_display_format: column.text,
    deadline_awareness_days: column.integer,
    default_time_zone_mode: column.text,
    language: column.text,
    locale: column.text,
    revision: column.integer,
    server_updated_at: column.text,
    time_display_format: column.text,
    time_zone: column.text,
    today_primary_lookahead_days: column.integer,
    updated_at: column.text,
    updated_by_device_id: column.text,
    user_id: column.text,
    weather_city: column.text,
    week_start_day: column.text,
  }),
});
